### ISSUE TITLE
literature search 

### ISSUE THREAD

**Issue by markziemann** [mandhri/hcymeth#1]
@mandhri please enter in the studies that you have already found into the literature.md file. Could you also include here your literature search method, for example which database was searched and what keywords were used and the date of the search.

@salehalobaidi once @mandhri has populated these studies can you please add the ones you have found including  your method

If you have any queries about doing the literature search feel free to reply here.

**Comment by mandhri** [comment]
@markziemann  I have already sent Saleh the methods to search the literature on 07/07/2020 since I can not remember the exact keywords I used in searching for one study. But I have mailed Saleh on the overall key words and databases I have extracted literature so far. I will update the literature md with the search method for new studies.

**Comment by mandhri** [comment]
@salehalobaidi I have updated the literature md for 7 studies. Kindly go through. I have updated the methodology file in google drive for you so that you can be familiarised with the methodology.

**Comment by salehalobaidi** [comment]
Hi @mandhri, I am so sorry but I was very busy in the last couple of days as I was moving to a new place. I will update the literature md tomorrow. Thanks for the keywords and the updated methodology.
